# Generated by Django 3.2 on 2022-08-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='street_address_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address2',
            new_name='street_address_2',
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='12345', max_length=20),
            preserve_default=False,
        ),
    ]
